### ISSUE TITLE
Future request: tab-able API accordion items

### ISSUE THREAD

**Issue by Nurech** [mintlify/docs#111]
Please make these tab-able and open-able by keyboard for accessibility reasons, thank you.

<img width="472" alt="image" src="https://github.com/mintlify/docs/assets/20840114/392da886-2354-4fa7-8a91-580b969beda4">

**Comment by rpmccarter** [comment]
Done! Thanks for pointing this out. There are a few other features that I'm struggling to find an accessibility solution for (the info hover, the type dropdown), but you should now be able to tab through the entire playground form
