### ISSUE TITLE
How to add a multilingual document?

### ISSUE THREAD

**Issue by azhengyongqin** [mintlify/docs#128]
### How to add a multilingual document?
like this: 
<img width="694" alt="image" src="https://github.com/mintlify/docs/assets/18138282/d92c47fa-aa2e-4db1-a923-b1e5ff644d9f">

**eg:** 
English: https://mintlify.com/en/docs/quickstart 
Chinese: https://mintlify.com/zh/docs/quickstart

**Comment by Jarcis-cy** [comment]
I also want to ask. I looked through the documentation and found that there seems to be no similar function description.
