### ISSUE TITLE
Issues with Category Names being included above the title of the pages on my docs.

### ISSUE THREAD

**Issue by ItsZeph** [mintlify/docs#222]
On the first page of my docs, it appears like this:
![image](https://github.com/user-attachments/assets/60530da0-be63-4a04-bedb-b9e1bcab203a)

However, on the other pages of my docs, it appears like this:
![image](https://github.com/user-attachments/assets/2aca9dd5-7c39-483a-8154-debb04794d82)

Is there anyway to have all of the pages have the category name on my docs?

**Comment by fmerian** [comment]
Hi @ItsZeph! May I ask if the repo where your docs are located is public? Alternatively, could you please send us an email at support@mintlify.com?

Thanks!

**Comment by fmerian** [comment]
Closing it for now. Keep us posted!
