### ISSUE TITLE
Frame Components Glass

### ISSUE THREAD

**Issue by grant** [mintlify/docs#232]
What is `type="glass"` on this page? It isn't documented in the props section.

https://mintlify.com/docs/content/components/frames

**Comment by Abhinavcode13** [comment]
fixed it, thanks for pointing it out!

**Comment by rpmccarter** [comment]
Thanks for letting us know! The `type="glass"` option has been removed, and it looks like the docs on it were also removed at some point

**Comment by grant** [comment]
Sounds good Ronan
