### ISSUE TITLE
Icons In List Bug

### ISSUE THREAD

**Issue by grant** [mintlify/docs#233]
https://mintlify.com/docs/content/components/icons

Icons look off when nested inside a list. I would assume they would not take a whole line, but would be inline.

For examples, allow icons to be used inline within bullet:

<img width="293" alt="Screenshot 2024-07-25 at 16 32 18" src="https://github.com/user-attachments/assets/b8cfaffe-4488-460f-87d4-8e5644b42e9c">

Example code:

```jsx
<Icon icon="check" iconType="solid" /> The documentation you want, effortlessly

- <Icon icon="check" iconType="solid" /> The documentation you want, effortlessly
```

**Comment by fmerian** [comment]
@grant Thanks for the report!

This should be fixed now:
![2024-11-05-8R2vtAJ1](https://github.com/user-attachments/assets/20a57ebe-8a35-45f5-ba3a-51a2a7484ba4)

Please let us know if it works on your side. Thanks!
