### ISSUE TITLE
More clear instructions on setting up a custom domain

### ISSUE THREAD

**Issue by eyalatiya** [mintlify/docs#240]
The docs aren't clear that `cname.vercel-dns.com` should be replace with `{my-domain}.vercel-dns.com`.
At least it didn't seem to work if I don't do this.
![image](https://github.com/user-attachments/assets/c2d93ecc-dc7e-4d9a-9322-642747821898)

**Comment by fmerian** [comment]
@eyalatiya Hello there! Thanks for the report!

We just updated the dashboard settings with clearer instructions to help you set up your custom domain, and related docs (#302).

Please let us know if it works!
