### ISSUE TITLE
Component reference pages often don't show code

### ISSUE THREAD

**Issue by kai687** [mintlify/docs#272]
Hi,

In your component reference, you often show only the result of a component, but not the code that lead to that result. For example, if I want to know how to add a frame around an image ([Frames](https://mintlify.com/docs/content/components/frames)), I have to look at the MDX file. (Not limited to the frames page

It would be nice if you could also show the code that lead to the final result, especially for people who aren't super familiar with MDX.

**Comment by fmerian** [comment]
Hi @kai687! Thanks for the suggestion.

In the example you provided, you should find the code examples on the right-hand side of the page.

Hope it helps!

I'm closing the issue for now. If you have any more questions, please do ask. Happy to help!

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/user-attachments/assets/4b23ba9d-9404-4642-9f1a-4c0917ca0d2f">
  <source media="(prefers-color-scheme: light)" srcset="https://github.com/user-attachments/assets/2474692e-4046-40b7-8172-a5fa6e0e072a">
  <img alt="Mintlify's Docs" src="https://github.com/user-attachments/assets/2474692e-4046-40b7-8172-a5fa6e0e072a">
</picture>

**Comment by fmerian** [comment]
no problem! some other pages in the docs have a different layout. that may be an explanation. good feedback!
