### ISSUE TITLE
Issue on docs: The Calendly link is invalid

### ISSUE THREAD

**Issue by JamieDawson** [mintlify/docs#276]
There is a broken Calendly link being used on two separate pages:

1) At the bottom of the [settings/gitlab.mdx](https://github.com/mintlify/docs/blob/0c52d221751eebfb163e00b69b300ca922deb4b7/settings/gitlab.mdx#L34) page
2) At the top of the [settings/authentication.mdx](https://github.com/mintlify/docs/blob/0c52d221751eebfb163e00b69b300ca922deb4b7/settings/authentication.mdx#L11) page

You can also search for ['Calendly' in the repo](https://github.com/search?q=repo%3Amintlify%2Fdocs%20calendly&type=code) to find both occurrences.

The link redirects to https://calendly.com/mintlify/demo-your-docs, which no longer works.

![Calendly](https://github.com/user-attachments/assets/0813bd6f-b676-4eb4-a6f6-892e540a1c18)

**Comment by fmerian** [comment]
spot on, @JamieDawson! just created a PR to fix it. thanks!
