### ISSUE TITLE
Get started button takes you to 404 page

### ISSUE THREAD

**Issue by nightspite** [mintlify/docs#70]
https://mintlify.com/docs/introduction

![CleanShot 2023-07-10 at 19 05 22](https://github.com/mintlify/docs/assets/26671956/0f5e35e4-ed36-4003-a267-4e1a11eef1d5)

![CleanShot 2023-07-10 at 19 06 27](https://github.com/mintlify/docs/assets/26671956/033541cb-8b75-4698-850b-8316dc6d52c5)

**Comment by hanywang2** [comment]
This has been fixed! Thank you for bringing it up ❤️
